/**
 * Terms of service.
 *
 * The price and the free-plan invoice cap are read from src/lib/pricing.ts
 * rather than typed here. Terms that contradict the pricing page are not a
 * cosmetic bug — they are the document someone waves at you in a chargeback.
 *
 * Two promises on this page are deliberately stronger than the legal minimum,
 * and both cost something to keep: your data stays exportable after you stop
 * paying, and a refund is available for a month you did not use. They are here
 * because a bookkeeping app that holds your records hostage is not a product
 * anyone should trust with their books.
 */

import { createFileRoute, Link } from "@tanstack/react-router";

import { LandingShell } from "@/components/landing/landing-shell";
import { Button } from "@/components/ui/button";
import { CONTACT_EMAIL } from "@/lib/contact";
import { LEGAL_UPDATED, LegalPage, LegalSection } from "@/components/landing/legal";
import { PLANS, TRIAL_DAYS, formatPrice } from "@/lib/pricing";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms — SimpleBooks" },
      {
        name: "description",
        content:
          "The terms you agree to when you use SimpleBooks: what it promises, how billing works, and what happens to your records.",
      },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  const proPrice = formatPrice(PLANS.pro.priceCents);
  const freeInvoiceCap = PLANS.free.limits.invoicesPerMonth;

  return (
    <LandingShell>
      <LegalPage title="Terms of Service" updated={LEGAL_UPDATED}>
        <p>
          These terms apply when you use SimpleBooks. Using the app means you accept them. They are
          written in plain English on purpose — terms nobody can read protect nobody.
        </p>

        <LegalSection title="What SimpleBooks is, and what it isn't">
          <p>
            SimpleBooks is a record-keeping tool. It helps you write down the money going in and out
            of your business, and shows you what that adds up to.
          </p>
          <p>
            <strong className="text-foreground">
              It is not an accountant, a bookkeeper, or a tax adviser.
            </strong>{" "}
            It does not file returns, it does not tell you what you owe, and its figures are not
            professional advice. Anything it estimates — set-aside amounts, runway, margins — is a
            calculation from the numbers you entered, nothing more. Check anything that matters with
            a qualified professional before acting on it.
          </p>
          <p>
            The answers given by the &ldquo;Ask about your money&rdquo; feature are generated by an
            AI model and can be wrong. Treat them as a starting point, not an authority.
          </p>
        </LegalSection>

        <LegalSection title="Your account">
          <p>
            You need an account to use the app, and you are responsible for keeping your password
            and app-lock PIN to yourself. Tell us if you think someone else has got into your
            account.
          </p>
          <p>
            You must be at least 13 years old, and old enough to enter a contract where you live.
          </p>
          <p>
            One account is for one person or business. If you share access through the household
            feature, you are responsible for who you invite and what they can then see.
          </p>
        </LegalSection>

        <LegalSection title="Your data belongs to you">
          <p>
            What you enter is yours. We do not claim ownership of it, we do not sell it, and we do
            not use it to train AI models. We store and process it only to run the service for you —
            the details are in the{" "}
            <Link className="text-brand hover:underline" to="/privacy">
              Privacy Policy
            </Link>
            .
          </p>
          <p>
            You can export everything as CSV or PDF at any time, from inside the app, on any plan.
            You do not have to ask, and you do not have to be paying.
          </p>
        </LegalSection>

        <LegalSection title="Your free trial">
          <p>
            <strong className="text-foreground">
              Pro is free for {TRIAL_DAYS} days. We take your card details when you start, and we do
              not charge them until day {TRIAL_DAYS + 1}.
            </strong>
          </p>
          <p>
            On that day your card is charged {proPrice}, and then {proPrice} every month after that,
            until you cancel.{" "}
            <strong className="text-foreground">
              Cancel at any point before the trial ends and you pay nothing at all.
            </strong>{" "}
            Cancelling takes one click from the Billing page — the same number of steps it took to
            start.
          </p>
          <p>
            While the trial is running, the app shows you how many days are left and the exact date
            and amount of the first charge. On the final day that notice cannot be dismissed. We
            would rather you cancel deliberately than be surprised by a charge.
          </p>
          <p>One trial per account.</p>
        </LegalSection>

        <LegalSection title="Plans and billing">
          <p>
            Pro costs {proPrice} per month, charged in US dollars, and renews automatically each
            month until you cancel.
          </p>
          <p>
            When a Pro subscription ends — because you cancelled, or a payment could not be taken —
            the account drops to the Free plan. Free costs nothing and has no time limit. You can
            still log money in and out, see your daily and monthly totals, use the app in any of the
            six languages, and export everything you have ever entered. Free does not include
            invoicing{freeInvoiceCap === 0 ? "" : ` beyond ${freeInvoiceCap} a month`}, receipt
            scanning, budgets and goals, household sharing, or asking questions about your figures.
          </p>
          <p>
            <strong className="text-foreground">Cancelling is one click, at any time</strong>, from
            Billing inside the app. You keep Pro until the end of the month you have already paid
            for, and you are not charged again. We will not ask you to email us or sit through a
            retention flow to leave.
          </p>
          <p>
            If a payment fails, we keep your access on while Stripe retries over the following days
            rather than cutting you off immediately.
          </p>
          <p>
            We may change the price. If we do, we will tell you at least 30 days before it affects
            you, and you can cancel before it takes effect. A price change never applies to a month
            you have already paid for.
          </p>
        </LegalSection>

        <LegalSection title="Refunds">
          <p>
            If you meant to cancel during the free trial and were charged anyway, email us and we
            will refund it. That is the whole rule — we will not ask you to prove you did not use
            it.
          </p>
          <p>
            If you were charged for a month you did not use, email{" "}
            <a className="text-brand hover:underline" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>{" "}
            within 30 days of the charge and we will refund it. If you were charged by mistake — a
            duplicate, or a subscription you cancelled — we will refund that regardless of when you
            noticed.
          </p>
        </LegalSection>

        <LegalSection title="If you stop paying, or we stop">
          <p>
            Dropping from Pro to Free does not delete anything. Your records stay, you can still
            open them, and you can still export the lot. Pro-only features stop; your books do not.
          </p>
          <p>
            If we ever shut the service down, we will give you at least 60 days&rsquo; notice and
            keep exports working for that whole period. Nobody should lose their business records
            because a small app went away.
          </p>
        </LegalSection>

        <LegalSection title="What you agree not to do">
          <p>
            Do not use SimpleBooks to break the law, to store other people&rsquo;s data without
            their knowledge, or to attack the service — no attempting to reach other users&rsquo;
            accounts, no probing for holes, no automated hammering that degrades it for everyone
            else.
          </p>
          <p>
            We may suspend an account that does these things. Where we can, we will warn you first
            and give you the chance to export your data.
          </p>
        </LegalSection>

        <LegalSection title="Availability">
          <p>
            We try to keep the app running and your data safe, but we do not promise it will never
            be down or never lose anything. The app works offline and queues entries so a lost
            connection does not cost you a day&rsquo;s takings — but{" "}
            <strong className="text-foreground">
              keep your own copy of anything you cannot afford to lose.
            </strong>{" "}
            Export regularly. This is good practice with any software, including ours.
          </p>
          <p>The service is provided as it is, without warranties of any kind.</p>
        </LegalSection>

        <LegalSection title="Limit of liability">
          <p>
            To the extent the law allows, SimpleBooks is not liable for indirect or consequential
            losses — lost profits, lost business, or decisions made on the basis of figures in the
            app. Our total liability to you is limited to what you paid us in the 12 months before
            the claim.
          </p>
          <p>
            Some places do not allow these limits, in which case they do not apply to you. Nothing
            here removes rights you have under consumer law that cannot be signed away.
          </p>
        </LegalSection>

        <LegalSection title="Changes to these terms">
          <p>
            We may update these terms. If a change materially affects you, we will tell you in the
            app before it takes effect rather than editing this page quietly. Continuing to use
            SimpleBooks after that means you accept the new version.
          </p>
        </LegalSection>

        <LegalSection title="Governing law">
          <p>
            SimpleBooks is operated from the United States and these terms are governed by United
            States law. Questions go to{" "}
            <a className="text-brand hover:underline" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </LegalSection>

        <div className="mt-10 flex flex-wrap gap-2">
          <Button asChild variant="outline">
            <Link to="/">Back to the home page</Link>
          </Button>
          <Button asChild variant="ghost">
            <Link to="/privacy">Read the Privacy Policy</Link>
          </Button>
        </div>
      </LegalPage>
    </LandingShell>
  );
}
